version: '3.3'

services:
  postgres_dz_db:
    image: postgres:14-alpine
    container_name: dz_db
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment: 
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_dz_db:/var/lib/postgresql/data
    networks:
      default:
        aliases:
          - dz_db
  redis_dz:
    image: "redis:latest"
    command: redis-server --requirepass ${REDIS_PASS}
    expose:
     - "6379"
    volumes:
      - redis-data:/data
      - redis-conf:/usr/local/etc/redis/redis.conf
  api:
    container_name: dz_api
    image: dz/api:latest
    build:
      context: "./server"
    expose:
      - "${API_PORT}"
    volumes:
      - ../server:/opt/api:Z
    ports:
      - "${API_PORT}:${API_PORT}"
    depends_on:
      - postgres_dz_db
    networks:
      default:
        aliases:
        - dz_api
    entrypoint: sh -c "yarn install -f && yarn run:dev"

volumes:
  postgres_dz_db:
  redis-data:
  redis-conf: